spring:
  application:
    name: hubstop.integration
  datasource:
    url: jdbc:h2:mem:hubstop
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

hubspot:
  oauth:
    client:
      id: ${HUBSPOT_CLIENT_ID}
      secret: ${HUBSPOT_CLIENT_SECRET}
      redirect:
        uri: ${HUBSPOT_REDIRECT_URI}
      scope: ${HUBSPOT_SCOPES}
      auth:
        url: ${HUBSPOT_AUTH_URL}

security:
  crypto:
    secret: ${SECURITY_CRYPTO_SECRET}