spring:
  application:
    name: hubstop.integration

hubspot:
  oauth:
    client:
      id: ${HUBSPOT_CLIENT_ID}
      secret: ${HUBSPOT_CLIENT_SECRET}
      redirect:
        uri: ${HUBSPOT_REDIRECT_URI}
      scope: ${HUBSPOT_SCOPES}
      auth:
        url: ${HUBSPOT_AUTH_URL}